### ISSUE TITLE
LPD files cannot be read anymore : 'beat_resolution' update

### ISSUE THREAD

**Issue by Natnatf** [salu133445/pypianoroll#11]
Hi,
first of all thanks for your work, this library have been very useful to me.

Since the 1.0.0 update when loading a npz file pypianoroll will look for the 'resolution' instead of 'beat_resolution' previously, all the npz files from the LPD dataset cannot be read anymore.
I fixed this by editing pypianoroll to read either 'resolution' and 'beat_resolution' attributes but this can't be considered as a permanent fix.
Anyway I was wondering if you intended to update the LPD dataset (I think I can do it on my own but didn't take the time to do it yet) ?

**Comment by sandip-baidya** [comment]
how did you fix the function to read "beat_resolution". I tried finding ways to modify a function that belongs to a third-party library but I couldn't find anything substantial.

**Comment by Natnatf** [comment]
In the **load** method in **inputs.py**, you modify line 51 to make it read either "resolution" and "beat_resolution"

        try:
            resolution = info_dict["resolution"]
        except KeyError:
            resolution = info_dict["beat_resolution"]

**Comment by salu133445** [comment]
This has been fixed in 5bcc941. It will now look for `beat_resolution` when `resolution` is not found.
