### ISSUE TITLE
multitrack.write("xxx.mid") can't work after 1.0+ versions

### ISSUE THREAD

**Issue by rgb000000** [salu133445/pypianoroll#14]
In new version, multitrack.tempo needs to be a np.ndarray. However, the code[here](https://github.com/salu133445/pypianoroll/blob/main/pypianoroll/outputs.py#L130) directly judges np.ndarray which will return an error "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"
Maybe what we need here is 
`
...
elif multitrack.tempo is not None:
...
`
In addition, after fixing this error, a new error have arisen in pretty-midi.
Both python3.8 and python3.6 have above errors.

Is it my environment that causes these problems?

**Comment by salu133445** [comment]
Looks like a bug. Thanks for reporting.

**Comment by salu133445** [comment]
Fixed by bafb3cf.
