### ISSUE TITLE
pip install pypianoroll成功了，怎么运行？

### ISSUE THREAD

**Issue by huasheng-yue** [salu133445/pypianoroll#16]
windows10+anaconda3+pycharm2020.3环境，照作者指示安装了，请问如何调试运行？

**Comment by huasheng-yue** [comment]
Thank you for your reply even that was not worked with some bugs such as:
Fig,ax=…
Track.pianoroll……

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by salu133445** [comment]
Thanks for reporting this. The examples are somewhat outdated. I will find time to update them.
