### ISSUE TITLE
The copy method for StandardTrack Class changes the new object's type of class

### ISSUE THREAD

**Issue by 15805383399** [salu133445/pypianoroll#21]
![截图_20214703114731](https://user-images.githubusercontent.com/76238405/116839609-93d5ac00-ac05-11eb-9ff0-3022a8410fef.png)
If you want to deepcopy an object of MultiTrack, the type of class for every track in the object will change into Track, no matter they are StandardTrack or BinaryTrack objects before.
Because in source code, the copy method for StandardTrack and BinaryTrack is inherit from the super class Track, and it is not overrided. 
![截图_20210103120147](https://user-images.githubusercontent.com/76238405/116840133-5d992c00-ac07-11eb-8beb-bc8736f1f5d2.png)
So once you call the copy method, you will create a Track object, even if the original track is a StandardTrack or BinaryTrack object.

**Comment by salu133445** [comment]
This has been fixed by 5b4ed92.
