### ISSUE TITLE
Issue with version

### ISSUE THREAD

**Issue by dedededefo** [salu133445/pypianoroll#26]
Hello, Where is the  function  get_ merged_pianoroll()  in Multitrack in 0.1.3 version, I can't find it in the new one

**Comment by salu133445** [comment]
Hi, it was renamed to `Multitrack.blend()` in MusPy>1.0.0. Sorry for the confusion.

**Comment by dedededefo** [comment]
Thank you very much. I've found it!Thanks

**Comment by dedededefo** [comment]
> 嗨，它`Multitrack.blend()`在 MusPy>1.0.0 中被重命名为。对困惑感到抱歉。

Hello, I'm sorry to bother you again! I want to merge the filtered tracks, but the filtered tracks are StandardTrack, which does not seem to have the function of merging pianoroll, such as Multitrack. blend(). I tried to use Multitrack (filtered sequence). blend(), but it cannot run. What should I do? Thank you

**Comment by dedededefo** [comment]
> 嗨，它`Multitrack.blend()`在 MusPy>1.0.0 中被重命名为。对困惑感到抱歉。

Thank you! I've solved it

**Comment by dedededefo** [comment]
> 谢谢！我已经解决了

Thank you ! I've solved it
