### ISSUE TITLE
Problems displaying piano roll at a given size

### ISSUE THREAD

**Issue by Clockmender** [salu133445/pypianoroll#5]
Hello,

Firstly I am very new to this, someone has told me of your work.

I am able to create piano roll, but cannot seem to display it other than at 640x480 size. I have tried for a very long time, but cannot seem to be able to use a defined "figure":

fig = plt.figure('10.5,4.8')

I always get 640x480 when I issue plt.plot command.

Are there any worked examples of this I can look at please?

**Comment by salu133445** [comment]
Hi, the following code snippet might help.
```python
from pypianoroll import Multitrack
m = Multitrack('test.npz')
fig, axs = m.plot()
fig.set_size_inches(16, 9)
```
Note that the `Multitrack.plot()` method will return the created figure and axes objects. You can then set the figure size by calling the `Figure.set_size_inches()` method.

**Comment by Clockmender** [comment]
Thank you for you reply. I am developing a system in Blender 3D Animation software, to use your Pypianoroll library to make a simple DAW driven from animated objects, or using the Piano Roll to animate objects. I'll keep you posted here with progress.

For the moment I am going to save the plot as an image file, then display that in Blender. I will use the Numpy array to generate sounds using AudaSpace library.

**Comment by salu133445** [comment]
The idea sounds pretty interesting. Looking forward to your results.

**Comment by Clockmender** [comment]
This is where I am at now:

![Screen Shot 2019-04-22 at 13 31 10](https://user-images.githubusercontent.com/29657804/56507126-41425f00-6518-11e9-8611-a25639afd5a0.png)

The two first larger pink nodes process and add notes to the Numpy Arrays, passing the Track to the next pink node, which combines the /tracks into a Multitrack, then plots this in the display underneath the Node Viewer, it also writes out a .npz save file.

The Arrays are saved as .npy files. At the moment, notes, or chords are added to the array using the buttons and inputs, however, I plan a graphical interface for this so the notes can be drawn in and moved/copied, etc. Notes are erased at present by adding a note/chord with 0 Velocity, this needs to be a better system and is on my ToDo list.

The Generate nodes take the note list from the Array and sorts it into separate sounds for each note, then mixes all of these together to form one sound for the Track, which is output to the Player node, which can also save this to a sound file (Flac at present.). Sound processing is done with AudaSpace Python library.

Cheers, Clock.

**Comment by salu133445** [comment]
Sorry that I forgot to reply you. This is super cool! I like this idea and look forward to the final system. Cheers!

**Comment by salu133445** [comment]
Close the issue as there has been no updates for months.

**Comment by raraz15** [comment]
Here is hove I solved it,

**fig, axs = plt.subplots(nrows=2, figsize=(20,8))
multitrack.plot(axs=axs)
plt.show()**

nrows must be equal to the number of tracks in the midi file.
