### ISSUE TITLE
Unexpected location for function plot_multitrack()

### ISSUE THREAD

**Issue by MaximusWhite** [salu133445/pypianoroll#7]
For some reason `pypianoroll.plot.plot_multitrack()` cannot be found. Instead, it is in `pypianoroll.multitrack.plot_multitrack()`, which is a bit different from documentation.
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-137-238f3cd64c5c> in <module>
     19 # plt.show()
     20 
---> 21 fig, axs = pypianoroll.plot.plot_multitrack(multitrack, xtick='step', mode='stacked')
     22 fig.set_size_inches(200, 5)
     23 plt.show()

AttributeError: 'function' object has no attribute 'plot_multitrack'
```

**Comment by salu133445** [comment]
Fixed in d912ed0. I renamed `pypianoroll.plot` module to `pypianoroll.visualization` to avoid name conflicts with the `pypianoroll.plot()` function. Thanks for pointing this out.
